defaults:
  - model: model1
  - _self_

raw: 
  path: data/raw
  types: [sin_plaga, plaga]

global_metric: 0.7

model:
  dir: models/regression
  name: model_regression
  artifact_path: validate-plague
  random_state: 42
  path: ${model.dir}/${model.name}.joblib

processed:
  dir: data/processed
  numpy: plagues_arrays
  x_train: 
    name: x_train.npy
    path: ${processed.dir}/${processed.numpy}/${processed.x_train.name}
  x_test:
    name: x_test.npy
    path: ${processed.dir}/${processed.numpy}/${processed.x_test.name}
  y_train: 
    name: y_train.npy
    path: ${processed.dir}/${processed.numpy}/${processed.y_train.name}
  y_test:
    name: y_test.npy
    path: ${processed.dir}/${processed.numpy}/${processed.y_test.name}  
  
mlflow:
  tracking_ui: https://dagshub.com/juferoto/mlops_project.mlflow
  username: juferoto
  password: cf82c40f8b92dc68201f69fbc923bb4129d215c5